package:
  name: pyrosetta

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ pin_compatible('numpy') }}
    - cmake
    - ninja
  host:
    - python
    - setuptools
    - numpy
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - zlib
    - pandas >=0.18
    - scipy >=1.0
    - traitlets
    - python-blosc
    - decorator 

test:
  commands:
    - python -m unittest pyrosetta.tests.distributed.test_smoke

about:
  home: http://rosettacommons.org
